### ISSUE TITLE
Tomorrow afternoon does not work

### ISSUE THREAD

**Issue by LiyinZ** [wanasit/chrono#126]
tmr/tomorrow alone or afternoon/night etc. alone does work but a combination of them does not

**Comment by penne12** [comment]
"Afternoon" is too ambiguous, for example, 12:00 is technically after... noon, but is normally not what people mean when they say "afternoon". You could make an assumption, but that's not the chrono's choice to make. You could easily create a custom parser, and even be 100% more awesome and let the user configure it, but that's outside of the scope of the main library. Though it would be an awesome npm module.

"Night" is a bit more tricky, as it is technically defined as the period of darkness in a 24 hour period. First, you have to know what time the sun rises and sets in a given area, meaning you'd have to have the user's ip (which is [annoying][so client ip] to get), or their geolocation, which is iffy to get from a user, especially in most places where Chrono is used. Plus, since in many applications, Chrono is run every time a user types, so doing an ajax request to both get the user's IP's geolocation and the location's sunrise and sunset time is overly time consuming and would slow the entire response, plus Chrono is synchronous, so it would require a complete rewrite.

Again, you can create a custom parser and make assumptions, but it's not chrono's job to make them.


[so client ip]: http://stackoverflow.com/questions/391979/how-to-get-clients-ip-address-using-javascript-only/32841164
