### ISSUE TITLE
Override parser

### ISSUE THREAD

**Issue by mcchrish** [wanasit/chrono#210]
Trying to make a custom parser for 4 digit year:
```js
const chrono = require('chrono-node')
const parser =  new chrono.Parser()

parser.pattern = () => {
  return /\d{4}/
}

parser.extract = (text, ref, match, opt) => {
  return new chrono.ParsedResult({
    ref,
    text: match[0],
    index: match.index,
    start: {
      year: parseInt(match[0])
    }
  })
}

const custom = new chrono.Chrono()
custom.parsers.unshift(parser)

module.exports = custom
```

But it doesn't parse anything:

```js
const result = custom.parse('2015')
console.log(result) // []
```

Both `push` or `unshift` doesn't seem to work neither.

**Comment by mcchrish** [comment]
Weird thing is that even when make it the only parser available, still doesn't work.
```js
custom.parsers = [parser]
```

**Comment by wanasit** [comment]
This is because [UnlikelyFormatFilter](https://github.com/wanasit/chrono/blob/6579bd04966fcc39d6a9adc9f237c530e17eec08/src/refiners/UnlikelyFormatFilter.js) prevents your 4 digits extraction. You can just pop it out.

```
custom.parsers.push(parser) // add your parser
custom.refinders.pop() // pop the filter out
// Then, this should work.
custom.parse('2015') 
```

ps. the filter is there for a reason. please check [test_en.js](https://github.com/wanasit/chrono/blob/ce9bb6400fba21d06771d721d765a6438e158d8e/test/test_en.js) to see how things could go wrong.
