### ISSUE TITLE
ForwardDate doesnt always work

### ISSUE THREAD

**Issue by bjolseth** [wanasit/chrono#295]
using forwarddate from today (thursday 13. June 2019):
` const time = chrono.en_GB.parse(text, Date.now(), { forwardDate: true });`

Works as expected: "vacation monday" => **2019-06-17**

Not as expected: "vacation monday - friday" => **2019-06-10 - 2019-06-14**

The end date is still in the future (tomorrow) but start day is in the past, although forwardDate from today is requested. Would have expected/wanted the result to be **2019-06-17 - 2019-06-21**

**Comment by Lovinity** [comment]
I could be wrong, but I believe this was by design. Since the current day is not monday, it goes to the next monday. However, because your range did not specify the next one, it assumes "if current date conforms to the specified range, use the range which the current date falls in." Therefore, you got a range where the start date was before, and end date after, the current one.

**Comment by wanasit** [comment]
Sorry for my super slow reply. I think this has already been fixed for a while.
(see. 63cd91b)
