### ISSUE TITLE
Parse reoccurring dates

### ISSUE THREAD

**Issue by atymic** [wanasit/chrono#349]
Any thoughts on supporting parsing reoccurring dates? For example:

`every day at 8am`
`every tue` 

etc

**Comment by rbk** [comment]
I like this idea, but maybe it is out of scope of this projects intention? Reoccurring dates seem to be specific to an applications purpose rather than just parsing the date. I do see the added value it would bring.

It seems like it would be pretty easy to parse "reoccurring" language and add a interval property to the result of parse.

**Comment by wanasit** [comment]
Hello. Sorry for my slow reply. I don't think Chrono would support recurring date parsing anytime soon.

Currently, Javascript doesn't have any standard support for recurring dates (both `Date` and the new [Temporal](https://tc39.es/proposal-temporal/docs/index.html)). Even if the library detects and recognizes those recurring examples that you give, it is difficult to design an output structure or API that makes it universally useful.

**Comment by rori4** [comment]
For anyone searching for solution here is a project that works like that https://github.com/yb66/tickle

**Comment by rori4** [comment]
I have found this for a way of adding recurring tasks alongside with `chrono-node`

This parses text as well and returns an object to get recurring task -> https://www.npmjs.com/package/parse-messy-schedule

This actually would be a great feature to be added to `chrono-node` but the devs have rejected the idea
