### ISSUE TITLE
Adding additional ES5-compatible dist

### ISSUE THREAD

**Issue by jcamilleri13** [wanasit/chrono#350]
I have the unfortunate and unenviable position of having to support IE11 on the app I'm currently working on. This library is a work of genius and immensely useful, however the final dist bundle is only transpiled down to ES6, which is wreaking havoc on my build process. Would it be possible to update the configuration to output 2 files, the current (sensible) ES6 version, and an additional ES5 version for legacy systems?

I believe this could be done by adding a separate tsconfig and executing the compiler twice. I could look into submitting a pull request if you're open to the idea. I completely understand if you're not though, I can figure out some work-around from my end in that case.

Thanks!

**Comment by wanasit** [comment]
Sorry for my slow reply. I'd like to help, but I am not really good at the configuration and I don't understand what you suggested.

If you could share a documentation about publishing ES5 in addition to ES6, I will try to read it. Or, just sending me an MR, so I could read and understand what you want to do is also a great option.

**Comment by benaubin** [comment]
Hi there! I would recommend adding babel to your rollup or webpack config to transpile chrono to ES5. You still have to transpile to handle modules, and IE11 is near EOL, so I don't see the advantage of providing first-class support in this library. Let me know if there's a compelling reason otherwise, and I'd be happy to reopen.
