### ISSUE TITLE
False positives when "at" is combined with numbers

### ISSUE THREAD

**Issue by KevinNovak** [wanasit/chrono#377]
I'm getting some false positives (using the strict English mode), for the following examples:

- "I'm at 101,194 points!" --> 1:01 AM
- "I'm only at 5 health" --> 5:00 AM

Perhaps for strict English mode an ":" or "am/pm" should be required when an "at" is also used?

Likely related to #374

**Comment by wanasit** [comment]
Thanks for reporting this. This is partially fixed in bf2ae34c8b9a5ed362a59a82c3e8453bf841f633.

However, we cannot really handle the second example ("I'm only at 5 health") correctly as we want to keep compatibility with casual date mentioned (e.g. "at 5" and "at 12.30"). 

I agree we should make the `strict` parsing more strict, which is not the case yet.

**Comment by KevinNovak** [comment]
Thank you! I just updated my project with the latest version and can confirm it did fix the "I'm at 101,194 points" example.

Do you plan not parsing "I'm only at 5 health" as a time for the `strict` mode? I think in the meantime, for my case, I'll end up capturing "at" + number scenarios and filtering them out before using Chrono to parse.

**Comment by wanasit** [comment]
This is fixed in b582ae74c37303a29c2def1715dfb6e741f14210.

**Comment by KevinNovak** [comment]
Thanks! When I went to go test this I experienced a build error (#381). I'll test again when I can!

**Comment by KevinNovak** [comment]
This fixes some scenarios, but others are still detected as times.

"I'm at 5 health" --> 5:00 AM
"I'm at 9 health" --> 9:00 AM
"I'm at 10 health" --> Not a time
"I'm at 11 health" --> Not a time
"I used 2-3 cups of flour in the recipe" --> 2:00 AM - 3:00 AM

Single digits seem to still be recognized as times.
