### ISSUE TITLE
Parse times in parenthesis, quotes, and other boundary-like characters

### ISSUE THREAD

**Issue by KevinNovak** [wanasit/chrono#383]
I noticed Chrono doesn't recognize times if they are surrounded by parenthesis.

**Want to meet for dinner (5pm EST)?** --> Does not parse
**Want to meet for dinner, 5pm EST?** --> 5:00 PM

I believe this is because Chrono considers parenthesis like normal characters (the same as if we were to do "X5pmX"), and not like boundary characters.

Similarly with quotes:

**He said "5pm"** --> Does not parse
**He said 5pm** --> 5:00 PM

Similar behavior for most boundary-like characters: `( ) [ ] { } < > " '`

**Comment by benaubin** [comment]
Thanks for the issue, @KevinNovak. I've marked this as an enhancement, as the goal of this issue is to make Chrono match more times, rather than fixing an implementation bug or false positives.

This may be quite difficult due to Chrono's internal architecture - we'd have to replace many of the regular expressions within the Chrono parsers. Likely, we could rely on `\b` to match word boundaries, even when there is no whitespace but a special character, in places where this is the desired behavior.

**Comment by KevinNovak** [comment]
I agree this would be an enhancement, and using `\b` to match word boundaries seems like a good idea.

I was curious which characters would be considered the edge of boundaries, and so I played around in a regex builder a bit. The dashed lines here are boundaries:

![image](https://user-images.githubusercontent.com/11231402/110575611-26d5f680-812d-11eb-8e7c-a10cc84f9d6e.png)

Saved regex: https://regex101.com/r/3aeahV/1

So I think this proves using `\b` could work for these scenarios.

**Comment by wanasit** [comment]
Fixed in 6a52cf3.

**Comment by KevinNovak** [comment]
> Fixed in 6a52cf3.

I can't find this commit, is this the right commit hash?

**Comment by wanasit** [comment]
oh sorry. I can't believe I just forgot to push the change.

**Comment by wanasit** [comment]
I replied the comment. Thanks for checking.

> I noticed this is not published to npm yet but maybe that is on purpose.

Yes. I still feel it's not well tested enough and I also would like to fix other issues as well if I have time this weekend.

**Comment by wanasit** [comment]
Published `2.2.6`
