### ISSUE TITLE
Add brazilian portuguese localization

### ISSUE THREAD

**Issue by lfbittencourt** [wanasit/chrono#41]
I'm struggling to add a brazilian portuguese localization to Chrono. I guess the instructions in #27 are pretty outdated, right? How can I do to achieve that nowadays?

**Comment by wanasit** [comment]
Hi, #27 is pretty outdated, but the idea is still applied.

You need to create new "parser" modules to make chrono recognize Brazilian's date pattern. Please, try following the section in the README file. (https://github.com/wanasit/chrono#parser)

After you understand how the parser works, I suggest you create a new folder in `src/parsers/PT_BR` and start working on your parsers. Try looking at example from other language such as `src/parsers/JP`.

Hope this help. (Please also feel free to fork and push some code to up Github, so that I may able to see your code and help you further.)

**Comment by lfbittencourt** [comment]
Thanks, @wanasit :-)

**Comment by bgbraga** [comment]
@lfbittencourt have you implemented it?

**Comment by lfbittencourt** [comment]
@bgbraga Nope.
