### ISSUE TITLE
Might be useful to handle year only, or month and year

### ISSUE THREAD

**Issue by philgooch** [wanasit/chrono#98]
Clearly there is a risk of ambiguity here, but arguably that's up to upstream/downstream code to handle. It would be good to be able to parse month and year (defaulting to the first of the month I guess), e.g.

`chrono.parseDate('June 2004')`

and

`chrono.parseDate('06/2004')`

**Comment by silentrob** [comment]
As a lurker of this project and other date parsing libs, Ive struggled with this ambiguity. I feel like the intent here is to capture not June 1 but a date range between June 1st - and June 30th.

**Comment by jonotron** [comment]
Would whole month date ranges be desired in all cases? I think in some contexts you might want to return a single date (as is current behaviour), e.g. "I started my diet in June". And in other contexts you might want a range, e.g. "Show me all my appointments for June".

So it seems to me that this should be an optional refiner that the developer might add depending on their use case.

I've started a refiner to return whole month ranges, e.g. "Jan - Feb" would return "Jan 1, 2016" to "Feb 29, 1026" (https://github.com/jonotron/chrono-refiner-wholemonth/blob/master/index.js).

It's working, for the most part, but possibly failing in certain situations. E.g. "Dec - Feb 2015" returns a start of "Feb 2015" and end of "Dec 2015". Chrono seems to get the order mixed up. I believe this is because it is incorrectly (incorrectly in my opinion) setting "Dec 2015" with a known year of "2015".

So I guess I have a few questions...

1. Any thoughts on if the idea behind this refiner that I wrote should be an external module (as I've assumed it to be so far)?
2. In my example case, "Dec - Feb 2015" is the behaviour of having the "Dec" component with a known year of "2015" the correct behaviour?
3. Should the order be fixed so that start: "Dec" and end: "Feb" is returned?

**Comment by penne12** [comment]
My thoughts:

1. It should probably be an external module - as it's not extremely useful for all users (still extremely useful for some).
2. Nope - that probably shouldn't happen. Dec-Feb 2015 probably means Dec [reference year or 2014 (which ever is sooner)] to Feb 2015. 
3. Yes - it should be.

**Comment by jonotron** [comment]
@penne12 Cool, thanks! I've made issue #104

**Comment by penne12** [comment]
I've closed the issue, let me know if there is still something needed.
